development:
  smtp:
    address: "smtp.gmail.com"
    port: 587
    domain:" yourdomain.com"
    authentication: :plain
    user_name: "youremailaddress@gmail.com"
    password: "yourpassword"
    enable_starttls_auto: true
production:
  smtp:
    address: "smtp.gmail.com"
    port: 587
    domain:" yourdomain.com"
    authentication: :plain
    user_name: "youremailaddress@gmail.com"
    password: "yourpassword"
    enable_starttls_auto: true
